name: Test Powershell
on: push

jobs:
  pester-test:
    name: Lab 2 Tests
    runs-on: windows-2019
    steps:
      - name: Check out repo        
        uses: actions/checkout@v2
      - run: Install-Module Pester -Force
      - run: Import-Module Pester -PassThru
      - run: |
          ./ICT_128_LAB_2.Tests.ps1